name: Crystal

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: crystal-lang/install-crystal@v1

    - run: shards install
    - run: crystal spec
